# Generated by Django 4.2.7 on 2023-11-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('idAdminCalificacion', models.AutoField(primary_key=True, serialize=False)),
                ('reto', models.CharField(max_length=255)),
                ('promedioFactible', models.FloatField()),
                ('promedioEstrategico', models.FloatField()),
                ('grupo', models.CharField(max_length=150)),
            ],
        ),
    ]
