# Generated by Django 4.2.7 on 2023-11-25 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion',
            old_name='idAdminCalificacion',
            new_name='idCalificacion',
        ),
    ]
